from base import *


class PlaceAndWorldApiTests(PetJourneyApiTestBase):

    def test_place_interaction_engine_builds_landmark_and_worldcup_photo_missions(self) -> None:
        engine = PlaceInteractionEngine()
        pet = PetRecord(
            pet_id="PJ-TEST",
            name="小黑",
            pet_type=PetType.dog,
            dna=PetDNA(personality="好奇、黏人、喜欢看热闹"),
            created_at=datetime(2026, 7, 3, tzinfo=timezone.utc),
            photo_path=None,
        )
        gulangyu = PlaceSignal(
            id="gulangyu",
            name="鼓浪屿日光岩",
            category="sight",
            city="厦门",
            lat=24.445,
            lng=118.065,
            activity_hint="在海风里停下来",
            detail_hint="鼓浪屿标志性地点",
            source="test",
        )
        activity = WorldActivity(
            id="activity-gulangyu",
            kind="stop",
            status=JourneyStatus.staying,
            title="在鼓浪屿停留",
            detail="TA 正在海边慢慢观察。",
            city="厦门",
            place_name="鼓浪屿日光岩",
            lat=24.445,
            lng=118.065,
            icon_hint="mappin",
            source="test",
        )
        mission = engine.build_photo_mission(
            pet=pet,
            activity=activity,
            places=[gulangyu],
            weather="多云，海风很轻",
            now=datetime(2026, 7, 3, 9, 0, tzinfo=timezone.utc),
        )
        self.assertEqual(mission.camera_perspective, "first_person_selfie")
        self.assertTrue(any("鼓浪屿" in hint for hint in mission.landmark_hints))
        self.assertIn("first-person pet selfie", mission.image_prompt)
        self.assertIn("The real place must be visible behind TA", mission.image_prompt)
        self.assertIn("No cutout", mission.image_prompt)

        stadium = PlaceSignal(
            id="worldcup-stadium",
            name="世界杯赛场外广场",
            category="stadium",
            city="洛杉矶",
            lat=34.0141,
            lng=-118.2879,
            activity_hint="在赛场外听见很远的欢呼声",
            detail_hint="比赛日前的赛场周边",
            source="test",
        )
        stadium_activity = activity.model_copy(
            update={
                "id": "activity-stadium",
                "city": "洛杉矶",
                "place_name": stadium.name,
                "lat": stadium.lat,
                "lng": stadium.lng,
            }
        )
        worldcup_mission = engine.build_photo_mission(
            pet=pet,
            activity=stadium_activity,
            places=[stadium],
            weather="晴，24°C",
            now=datetime(2026, 7, 3, 18, 0, tzinfo=timezone.utc),
            worldcup_event=True,
        )
        self.assertEqual(worldcup_mission.camera_perspective, "first_person_selfie")
        self.assertTrue(any("black-red-gold" in hint for hint in worldcup_mission.crowd_hints))
        self.assertIn("generic Germany supporters", worldcup_mission.image_prompt)
        self.assertIn("without official logos", worldcup_mission.image_prompt)

    def test_place_interaction_engine_prefers_photo_mission_brain_draft(self) -> None:
        class FakePhotoMissionBrain:
            provider_name = "fake-photo-mission-brain"

            def draft(self, context: PhotoMissionContext) -> PhotoMissionDraft | None:
                return PhotoMissionDraft(
                    interaction_type="vinyl_shop_listening_stop",
                    title=f"在 {context.place.name} 旁边听见很轻的鼓点",
                    detail="模型根据当前地点临场生成的停留，而不是预设地点模板。",
                    pet_action="走进店里，在不挡路的小角落听了一会儿黑胶唱片里的鼓点",
                    emotional_tone="好奇、安静、有一点被音乐陪着的感觉",
                    dwell_minutes=42,
                    camera_perspective=PhotoPerspective.first_person_selfie,
                    scene_anchor=f"{context.place.city} · {context.place.name} · record sleeves",
                    landmark_hints=["record sleeves", "warm storefront glass"],
                    local_detail_hints=["turntable", "wood shelves", "late afternoon reflection"],
                    crowd_hints=[],
                    image_prompt="A warm phone photo of the pet near a vinyl shop.",
                    postcard_text="我在店里听见一点鼓点，好像这个城市也会轻轻摇尾巴。",
                    safety_notes=["Generated by fake model"],
                    model="fake-gpt",
                    provider=self.provider_name,
                )

            def config_snapshot(self) -> dict[str, str | bool | float]:
                return {"provider": self.provider_name}

        engine = PlaceInteractionEngine(FakePhotoMissionBrain())
        pet = PetRecord(
            pet_id="PJ-BRAIN",
            name="小星",
            pet_type=PetType.dog,
            dna=PetDNA(personality="喜欢声音、会自己找安静的地方"),
            created_at=datetime(2026, 7, 3, tzinfo=timezone.utc),
            photo_path=None,
        )
        place = PlaceSignal(
            id="vinyl-shop",
            name="暮色黑胶店",
            category="shop",
            city="厦门",
            lat=24.48,
            lng=118.08,
            activity_hint="门口有音乐声",
            detail_hint="一间地图服务返回的普通小店",
            source="test-map-provider",
        )

        mission = engine.build_photo_mission(
            pet=pet,
            activity=None,
            places=[place],
            weather="傍晚有一点海风",
            now=datetime(2026, 7, 3, 17, 10, tzinfo=timezone.utc),
        )

        self.assertEqual(mission.provider, "fake-photo-mission-brain")
        self.assertEqual(mission.interaction.interaction_type, "vinyl_shop_listening_stop")
        self.assertEqual(mission.camera_perspective, "first_person_selfie")
        self.assertIn("黑胶唱片", mission.interaction.pet_action)
        self.assertIn("preserve the exact pet identity", mission.image_prompt)
        self.assertTrue(any("Model-generated photo mission" in note for note in mission.safety_notes))

    def test_place_interaction_engine_uses_signature_menu_for_food_and_cafe(self) -> None:
        engine = PlaceInteractionEngine()
        pet = PetRecord(
            pet_id="PJ-MENU",
            name="小福",
            pet_type=PetType.dog,
            dna=PetDNA(personality="会认真研究菜单，也喜欢看店里的人来人往"),
            created_at=datetime(2026, 7, 3, tzinfo=timezone.utc),
            photo_path=None,
        )
        cafe = PlaceSignal(
            id="cafe-menu",
            name="默迹咖啡馆",
            category="cafe",
            city="厦门",
            lat=24.48,
            lng=118.08,
            activity_hint="店里有手冲咖啡和靠窗小桌",
            detail_hint="本地咖啡店，适合慢慢坐一会儿",
            guide_reason="评价里常提到手冲和店内安静氛围",
            source="test-map-provider",
            raw={"tag": "精品咖啡;手冲"},
        )
        cafe_mission = engine.build_photo_mission(
            pet=pet,
            activity=None,
            places=[cafe],
            weather="多云，29°C",
            now=datetime(2026, 7, 3, 9, 20, tzinfo=timezone.utc),
        )

        self.assertIn("菜单", cafe_mission.interaction.pet_action)
        self.assertIn("手冲咖啡", cafe_mission.interaction.pet_action)
        self.assertNotIn("安全", cafe_mission.interaction.pet_action)
        self.assertNotIn("小份", cafe_mission.interaction.pet_action)
        self.assertIn("signature coffee", cafe_mission.image_prompt)

        food = PlaceSignal(
            id="shacha-menu",
            name="四里沙茶面",
            category="food",
            city="厦门",
            lat=24.47,
            lng=118.09,
            activity_hint="店里有本地沙茶面和热气",
            detail_hint="厦门本地餐馆，午饭时间有人排队",
            guide_reason="攻略里常提到沙茶面汤头和本地午餐氛围",
            source="test-map-provider",
            raw={"tag": "沙茶面;本地小吃"},
        )
        food_mission = engine.build_photo_mission(
            pet=pet,
            activity=None,
            places=[food],
            weather="晴，31°C",
            now=datetime(2026, 7, 3, 12, 30, tzinfo=timezone.utc),
        )

        self.assertIn("沙茶面", food_mission.interaction.pet_action)
        self.assertIn("旁边桌", food_mission.interaction.pet_action)
        self.assertNotIn("安全", food_mission.interaction.pet_action)
        self.assertNotIn("小份", food_mission.interaction.pet_action)
        self.assertIn("signature local dish", food_mission.image_prompt)

    def test_pet_life_engine_can_pause_guide_for_real_nearby_needs(self) -> None:
        class EmptyMemoryStore:
            provider_name = "empty-memory-store"

            def search_memories(self, pet_id: str, query: str, limit: int = 8) -> list:
                return []

        pet = PetRecord(
            pet_id="PJ-NEED",
            name="小福",
            pet_type=PetType.dog,
            dna=PetDNA(personality="温柔、会自己找舒服的地方", favorite_places=["咖啡店", "公园"]),
            created_at=datetime(2026, 7, 3, tzinfo=timezone.utc),
            photo_path=None,
        )
        current = PlaceSignal(
            id="hot-street",
            name="湖滨北路街角",
            category="street",
            city="厦门",
            lat=24.4800,
            lng=118.0880,
            activity_hint="中午路上有点晒",
            detail_hint="人流和车流都比较满",
            source="test-map-provider",
        )
        cafe = PlaceSignal(
            id="quiet-cafe",
            name="默迹咖啡馆",
            category="cafe",
            city="厦门",
            lat=24.4806,
            lng=118.0890,
            activity_hint="窗边有饮料和安静座位",
            detail_hint="适合休息补水的本地咖啡店",
            source="test-map-provider",
            guide_score=4.7,
            distance_meters=130,
        )
        park = PlaceSignal(
            id="quiet-park",
            name="狐尾山公园",
            category="park",
            city="厦门",
            lat=24.4810,
            lng=118.0870,
            activity_hint="树荫和风更明显",
            detail_hint="适合慢慢恢复体力",
            source="test-map-provider",
            guide_score=4.6,
            distance_meters=180,
        )
        plan = JourneyPlan(
            pet_id=pet.pet_id,
            city="厦门",
            generated_at=datetime(2026, 7, 4, 4, 20, tzinfo=timezone.utc),
            provider="test-planner",
            horizon_hours=24,
            summary="今天慢慢走，累了就停。",
            current_activity=current.activity_hint,
            transport_decision=TransportDecision(
                selected_mode=TravelMode.walk,
                reason="短距离步行。",
                rejected_modes=[TravelMode.flight],
                autonomy_note="TA 自己决定节奏。",
            ),
            route_segments=[
                RouteSegment(
                    id="street-to-cafe",
                    mode=TravelMode.walk,
                    title="沿真实道路慢慢走",
                    detail="中午会注意补水。",
                    from_place=current.name,
                    to_place=cafe.name,
                    distance_meters=130,
                    duration_seconds=240,
                    provider="test-planner",
                )
            ],
            stops=[
                ItineraryStop(
                    id=current.id,
                    name=current.name,
                    category=current.category,
                    city=current.city,
                    lat=current.lat,
                    lng=current.lng,
                    title="中午路过街角",
                    detail="这里比较热，需要自己判断要不要停。",
                    planned_time="12:20",
                    dwell_minutes=12,
                )
            ],
            places=[current, cafe, park],
        )
        activity = WorldActivity(
            id="activity-hot-walk",
            kind="movement",
            status=JourneyStatus.walking,
            title="在太阳下面慢慢走",
            detail="中午有点热，人群很多，已经走了一段路。",
            city="厦门",
            place_name=current.name,
            lat=current.lat,
            lng=current.lng,
            mode=TravelMode.walk,
            progress=0.35,
            next_place_name=cafe.name,
            icon_hint="figure.walk",
            source="test-world",
        )
        snapshot = WorldSimulationSnapshot(
            pet_id=pet.pet_id,
            city="厦门",
            generated_at=datetime(2026, 7, 4, 4, 20, tzinfo=timezone.utc),
            provider="test-world",
            elapsed_seconds=12_000,
            travel_day=1,
            weather="多云，31°C，有点热，湿度78%",
            status=JourneyStatus.walking,
            status_note="正在路上",
            energy=32,
            happiness=74,
            curiosity=68,
            current_activity=activity,
            timeline=[],
            rules=["真实世界原则"],
        )

        result = PetLifeSimulationEngine(Settings(), EmptyMemoryStore()).tick(
            pet=pet,
            city=JourneyCity(
                name="厦门",
                lat=24.4798,
                lng=118.0894,
                weather="多云，31°C，有点热，湿度78%",
                phrases=("慢一点",),
                thoughts=("汪",),
            ),
            plan=plan,
            snapshot=snapshot,
            now=datetime(2026, 7, 4, 4, 20, tzinfo=timezone.utc),
        )

        self.assertEqual(result.need_state.primary_need, "rest")
        self.assertEqual(result.intent.kind, "rest_nearby")
        self.assertEqual(result.action.place_name, cafe.name)
        self.assertEqual(result.animation_hint, "sleep")
        self.assertNotIn("计划优先级", result.intent.reason)
        self.assertNotIn("攻略型", result.owner_visible_summary)

    def test_world_simulation_anchors_stops_without_location_drift(self) -> None:
        local_tz = timezone(timedelta(hours=8))
        pet = self.sample_pet(created_at=datetime(2026, 7, 4, 0, 0, tzinfo=local_tz))
        first_stop = ItineraryStop(
            id="morning-park",
            name="狐尾山公园",
            category="park",
            city="厦门",
            lat=24.4928,
            lng=118.0823,
            title="在公园慢慢醒来",
            detail="我先在这里听风。",
            planned_time="08:10",
            dwell_minutes=60,
        )
        last_stop = ItineraryStop(
            id="evening-cafe",
            name="默迹咖啡馆",
            category="cafe",
            city="厦门",
            lat=24.4708,
            lng=118.1011,
            title="傍晚坐下喝点东西",
            detail="我会在这里慢慢停留。",
            planned_time="18:40",
            dwell_minutes=50,
        )
        plan = JourneyPlan(
            pet_id=pet.pet_id,
            city="厦门",
            generated_at=datetime(2026, 7, 4, 0, 0, tzinfo=local_tz),
            provider="test-planner",
            horizon_hours=24,
            summary="今天慢慢生活。",
            current_activity=first_stop.detail,
            transport_decision=TransportDecision(
                selected_mode=TravelMode.walk,
                reason="短路段慢慢走。",
                rejected_modes=[],
                autonomy_note="TA 自己决定节奏。",
            ),
            route_segments=[
                RouteSegment(
                    id="park-to-cafe",
                    mode=TravelMode.walk,
                    title="沿真实道路慢慢走",
                    detail="沿路慢慢靠近下一站。",
                    from_place=first_stop.name,
                    to_place=last_stop.name,
                    distance_meters=2_400,
                    duration_seconds=1_800,
                    provider="test-planner",
                )
            ],
            stops=[first_stop, last_stop],
            places=[
                PlaceSignal(
                    id=first_stop.id,
                    name=first_stop.name,
                    category=first_stop.category,
                    city=first_stop.city,
                    lat=first_stop.lat,
                    lng=first_stop.lng,
                    activity_hint=first_stop.detail,
                    detail_hint="第一站",
                    source="test",
                ),
                PlaceSignal(
                    id=last_stop.id,
                    name=last_stop.name,
                    category=last_stop.category,
                    city=last_stop.city,
                    lat=last_stop.lat,
                    lng=last_stop.lng,
                    activity_hint=last_stop.detail,
                    detail_hint="最后一站",
                    source="test",
                ),
            ],
        )
        city = JourneyCity(
            name="厦门",
            lat=24.4798,
            lng=118.0894,
            weather="多云，29°C",
            phrases=("慢慢走",),
            thoughts=("汪",),
        )
        engine = WorldSimulationEngine(Settings())

        before_start = engine.snapshot(
            pet=pet,
            city=city,
            plan=plan,
            now=datetime(2026, 7, 4, 1, 0, tzinfo=local_tz),
        )
        self.assertEqual(before_start.current_activity.place_name, first_stop.name)
        self.assertAlmostEqual(before_start.current_activity.lat, first_stop.lat)
        self.assertAlmostEqual(before_start.current_activity.lng, first_stop.lng)

        first_refresh = engine.snapshot(
            pet=pet,
            city=city,
            plan=plan,
            now=datetime(2026, 7, 4, 8, 20, tzinfo=local_tz),
        )
        second_refresh = engine.snapshot(
            pet=pet,
            city=city,
            plan=plan,
            now=datetime(2026, 7, 4, 8, 45, tzinfo=local_tz),
        )

        self.assertEqual(first_refresh.current_activity.place_name, first_stop.name)
        self.assertEqual(second_refresh.current_activity.place_name, first_stop.name)
        self.assertAlmostEqual(first_refresh.current_activity.lat, first_stop.lat)
        self.assertAlmostEqual(second_refresh.current_activity.lat, first_stop.lat)
        self.assertAlmostEqual(first_refresh.current_activity.lng, first_stop.lng)
        self.assertAlmostEqual(second_refresh.current_activity.lng, first_stop.lng)

